Repository Letifery/swp-honeybees, pull requests merged in 2022-07, with the labels that each got.

#4 Updated classname and moved to models
  models/cnn2D.py
Labels: enhancement

#3 initial commit
  utils/dataloader 1.0.0.py
Labels: enhancement

#5 Update dataloader 1.0.0.py
  utils/dataloader 1.0.0.py
Labels: enhancement

#6 Dataloader update v1.1.0
  utils/dataloader-v1.1.0.py
Labels: enhancement

#7 initial commit
  utils/preprocessing-v1.0.0.py
Labels: enhancement

#8 Update to v1.1.0
  utils/preprocessing.py
Labels: enhancement

#9 Initial upload
  utils/logger.py
Labels: enhancement

#10 Update to v1.2.0
  utils/preprocessing.py
Labels: enhancement

#12 Update cnn2D.py
  models/cnn2D.py
Labels: enhancement

#13 Update cnn2D.py
  models/cnn2D.py
Labels: bug fix

#17 Update ppevaluation.py
  ppevaluation.py
Labels: enhancement

#15 Update cnn2D.py
  models/cnn2D.py
Labels: enhancement

#14 Update to v1.0.1
  utils/logger.py
Labels: bug fix

#19 ppevaluation-v2.0.0
  ppevaluation.py
Labels: enhancement, bug fix

#18 Mac support and option to specify delimiter
  utils/logger.py
Labels: enhancement, bug fix

#20 Update preprocessing.py
  utils/preprocessing.py
Labels: enhancement

#23 Update ppevaluation.py
  ppevaluation.py
Labels: bug fix

#22 Review Visualizer
  utils/reviewvisualizer.py
Labels: enhancement
